"""
Barrier Report Model - Contains analysis results
"""

from dataclasses import dataclass
from typing import Dict, List, Tuple


@dataclass
class BarrierReport:
    """
    Complete barrier analysis report for an SME
    """
    
    company_name: str
    barrier_score: float  # 0.0 (no barriers) to 1.0 (maximum barriers)
    risk_level: str  # "LOW", "MEDIUM", "HIGH"
    success_probability: float  # 0.0 to 1.0 (probability of successful MSSP adoption)
    dimension_scores: Dict[str, float]  # Scores for each Q-RCTM dimension
    barriers: List[Tuple[str, float, str]]  # (dimension, score, severity)
    recommendations: List[Dict[str, str]]  # List of actionable recommendations
    
    def get_summary(self) -> str:
        """
        Generate a human-readable summary of the report
        
        Returns:
            Formatted summary string
        """
        summary = []
        summary.append(f"CyberBarrier AI™ Analysis Report - {self.company_name}")
        summary.append("=" * 60)
        summary.append(f"\nRisk Level: {self.risk_level}")
        summary.append(f"Barrier Score: {self.barrier_score:.2f} / 1.00")
        summary.append(f"Success Probability: {self.success_probability:.1%}")
        summary.append("\nQ-RCTM v2.0 Dimension Scores:")
        
        for dimension, score in self.dimension_scores.items():
            dimension_display = dimension.replace('_', ' ').title()
            summary.append(f"  - {dimension_display}: {score:.2f}")
        
        summary.append(f"\nIdentified Barriers ({len(self.barriers)}):")
        for dimension, score, severity in self.barriers[:5]:  # Top 5
            dimension_display = dimension.replace('_', ' ').title()
            summary.append(f"  [{severity}] {dimension_display}: {score:.2f}")
        
        summary.append(f"\nRecommendations ({len(self.recommendations)}):")
        for i, rec in enumerate(self.recommendations[:3], 1):  # Top 3
            summary.append(f"  {i}. {rec['title']}")
        
        return "\n".join(summary)
    
    def get_detailed_report(self) -> str:
        """
        Generate a detailed report with all information
        
        Returns:
            Formatted detailed report string
        """
        report = []
        report.append("=" * 80)
        report.append(f"CyberBarrier AI™ - MSSP Implementation Barrier Analysis")
        report.append(f"Q-RCTM v2.0 Diagnostic Report")
        report.append("=" * 80)
        report.append(f"\nCompany: {self.company_name}")
        report.append(f"Analysis Date: [Generated by Q-RCTM v2.0 Engine]\n")
        
        # Executive Summary
        report.append("EXECUTIVE SUMMARY")
        report.append("-" * 80)
        report.append(f"Risk Level: {self.risk_level}")
        report.append(f"Overall Barrier Score: {self.barrier_score:.2f} / 1.00")
        report.append(f"MSSP Adoption Success Probability: {self.success_probability:.1%}")
        
        if self.risk_level == "HIGH":
            report.append("\n⚠️  HIGH RISK: Significant barriers detected. MSSP adoption likely to fail")
            report.append("    without addressing critical issues.")
        elif self.risk_level == "MEDIUM":
            report.append("\n⚠️  MEDIUM RISK: Notable barriers present. Recommend addressing key issues")
            report.append("    before MSSP implementation.")
        else:
            report.append("\n✓  LOW RISK: Company shows good readiness for MSSP adoption.")
        
        # Dimension Analysis
        report.append("\n\nQ-RCTM v2.0 DIMENSION ANALYSIS")
        report.append("-" * 80)
        
        dimension_names = {
            'risk_awareness': 'Risk Awareness',
            'capability': 'Security Capability',
            'technology_readiness': 'Technology Readiness',
            'management_support': 'Management Support'
        }
        
        for dimension, score in self.dimension_scores.items():
            name = dimension_names.get(dimension, dimension)
            barrier = 1.0 - score
            report.append(f"\n{name}:")
            report.append(f"  Maturity Score: {score:.2f} / 1.00")
            report.append(f"  Barrier Impact: {barrier:.2f}")
            
            if barrier >= 0.7:
                report.append(f"  Status: ⚠️  CRITICAL - Immediate attention required")
            elif barrier >= 0.5:
                report.append(f"  Status: ⚠️  HIGH - Should be addressed soon")
            elif barrier >= 0.3:
                report.append(f"  Status: ⚠️  MEDIUM - Monitor and improve")
            else:
                report.append(f"  Status: ✓  GOOD - Acceptable level")
        
        # Critical Barriers
        report.append("\n\nCRITICAL BARRIERS IDENTIFIED")
        report.append("-" * 80)
        
        critical_barriers = [b for b in self.barriers if b[2] in ['CRITICAL', 'HIGH']]
        if critical_barriers:
            for i, (dimension, score, severity) in enumerate(critical_barriers, 1):
                name = dimension_names.get(dimension, dimension.replace('_', ' ').title())
                report.append(f"\n{i}. {name}")
                report.append(f"   Severity: {severity}")
                report.append(f"   Barrier Score: {score:.2f}")
        else:
            report.append("\nNo critical barriers identified.")
        
        # Recommendations
        report.append("\n\nRECOMMENDATIONS")
        report.append("-" * 80)
        
        for i, rec in enumerate(self.recommendations, 1):
            report.append(f"\n{i}. {rec['title']}")
            report.append(f"   Dimension: {rec['dimension'].replace('_', ' ').title()}")
            report.append(f"   Priority: {rec['severity']}")
            report.append("   Recommended Actions:")
            for action in rec['actions']:
                report.append(f"     • {action}")
        
        if not self.recommendations:
            report.append("\nNo specific recommendations at this time. Continue monitoring.")
        
        report.append("\n" + "=" * 80)
        report.append("End of Report")
        report.append("=" * 80)
        
        return "\n".join(report)
    
    def to_dict(self) -> dict:
        """Convert report to dictionary format"""
        return {
            'company_name': self.company_name,
            'barrier_score': self.barrier_score,
            'risk_level': self.risk_level,
            'success_probability': self.success_probability,
            'dimension_scores': self.dimension_scores,
            'barriers': [(d, s, sev) for d, s, sev in self.barriers],
            'recommendations': self.recommendations
        }
